### ISSUE TITLE
Running out of memory when using Homestead

### ISSUE THREAD

**Issue by neilhamilton** [derekmd/laravel-dusk-firefox#1]
@derekmd thank you for this package

I'm finding I'm not able to install this package due to memory size exceeding:

```
PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Solver.php on line 223

```

I'm running this inside Homestead... Any ideas?

**Comment by derekmd** [comment]
Hey Neil,

This would be a Composer issue since the failure is happening in its codebase. You can try increasing the `memory_limit` value in the php.ini file or setting it to `-1` to disable memory checks. https://www.php.net/manual/en/ini.core.php#ini.memory-limit

Have a look at issue threads in the Composer repo: https://github.com/composer/composer/issues?q=is%3Aissue+%22Allowed+memory+size%22 After briefly scanning recent conversations, you may need to upgrade your global Composer install to the latest version since some older releases had higher memory use.
