### ISSUE TITLE
not working with laravel 11, laravel dusk 8.2.9

### ISSUE THREAD

**Issue by sajid-deltashoppe** [derekmd/laravel-dusk-firefox#34]

**Comment by derekmd** [comment]
This repository's composer.json dependencies will need to be bumped for Laravel Dusk v8. I'll see if I can find the time on the weekend to test a Laravel 11 project with that enabled.

This package has become less relevant since configuring Selenium, PhantomJS, etc. for any browser support is easy: https://laravel.com/docs/11.x/dusk#using-other-browsers

**Comment by derekmd** [comment]
A new major version release v3.0.0 is now available: https://github.com/derekmd/laravel-dusk-firefox/releases/tag/v3.0.0
